server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: ${spring.servlet.multipart.max-file-size}
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://52.79.93.170:3306/tagging_prod
    username: root
    password: ON_SECRET
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user1
      password: 1234
custom:
  temp:
    dirPath: ${HOME}/Desktop/os/temp
  gen:
    dirPath: ${HOME}/Desktop/os/temp/tagging_dev/gen